In [1]:
import tensorflow as tf
from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt
import numpy as np

In [2]:
(X_train, y_train), (X_test, y_test) = datasets.cifar10.load_data()
X_train.shape

(50000, 32, 32, 3)

In [3]:
y_train = y_train.reshape(-1,)
y_train

array([6, 9, 9, ..., 9, 1, 1], dtype=uint8)

In [4]:
classes = ["airplane", "automobile", "bird", "cat", "deer", "dog", "frog", "house", "ship", "truck"]

In [5]:
def plot_sample(X,y,index):
    plt.figure(figsize=(15,2))
    plt.imshow(X[index])
    plt.xlabel(classes[y[index]])

In [6]:
X_train = X_train/255
X_test = X_test/255

In [7]:
cnn = models.Sequential([
    layers.Conv2D(filters=32, kernel_size=(3, 3), activation='relu', input_shape=(32, 32, 3)),
    layers.MaxPooling2D((2, 2)),
    
    layers.Conv2D(filters=64, kernel_size=(3, 3), activation='relu'),
    layers.MaxPooling2D((2, 2)),
    
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

In [8]:
cnn.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [9]:
tf.config.experimental.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [10]:
tf.test.is_built_with_cuda()

True

In [11]:
%%timeit -n1 -r1
with tf.device('/GPU:5'):
    cnn.fit(X_train, y_train, epochs=15)

Epoch 1/15
1563/1563 [==============================] - 7s 3ms/step - loss: 1.4371 - accuracy: 0.4851
Epoch 2/15
1563/1563 [==============================] - 5s 3ms/step - loss: 1.0854 - accuracy: 0.6208
Epoch 3/15
1563/1563 [==============================] - 5s 3ms/step - loss: 0.9613 - accuracy: 0.6633
Epoch 4/15
1563/1563 [==============================] - 5s 3ms/step - loss: 0.8778 - accuracy: 0.6951
Epoch 5/15
1563/1563 [==============================] - 5s 3ms/step - loss: 0.8062 - accuracy: 0.7197
Epoch 6/15
1563/1563 [==============================] - 5s 3ms/step - loss: 0.7487 - accuracy: 0.7408
Epoch 7/15
1563/1563 [==============================] - 5s 3ms/step - loss: 0.6960 - accuracy: 0.7562
Epoch 8/15
1563/1563 [==============================] - 5s 3ms/step - loss: 0.6534 - accuracy: 0.7713
Epoch 9/15
1563/1563 [==============================] - 5s 3ms/step - loss: 0.6149 - accuracy: 0.7852
Epoch 10/15
1563/1563 [==============================] - 5s 3ms/step - loss: 0.575

In [12]:
cnn.evaluate(X_test, y_test)

313/313 [==============================] - 1s 2ms/step - loss: 1.0753 - accuracy: 0.6980


[1.075317621231079, 0.6980000138282776]

In [13]:
y_pred = cnn.predict(X_test)
y_pred

array([[3.42237081e-06, 1.20588493e-05, 1.20971301e-04, ...,
        3.39368341e-07, 1.20896474e-01, 1.07042863e-04],
       [1.01190271e-05, 1.15020150e-04, 1.01863042e-08, ...,
        1.23100922e-11, 9.99873996e-01, 7.84672977e-07],
       [1.12918146e-01, 6.42383099e-03, 1.10098440e-03, ...,
        1.58339981e-02, 7.35645831e-01, 6.81725144e-02],
       ...,
       [1.55948854e-07, 5.96119334e-11, 1.55788632e-02, ...,
        6.17170744e-02, 4.22999474e-05, 5.39852274e-10],
       [4.12824657e-03, 2.68514752e-01, 8.35172614e-05, ...,
        5.89194713e-07, 5.35289478e-03, 1.09974913e-04],
       [4.75585011e-06, 1.36398776e-05, 1.28196349e-04, ...,
        9.97722208e-01, 1.47765077e-05, 2.16597414e-07]], dtype=float32)

In [19]:
y_classes = [np.argmax(element) for element in y_pred]
y_classes[:5]
y_test = y_test.reshape(-1,)
y_test[:5]

array([3, 8, 8, 0, 6], dtype=uint8)

In [20]:
y_classes[:5]

[3, 8, 8, 0, 6]

In [22]:
from sklearn.metrics import confusion_matrix , classification_report
import numpy as np
y_pred = cnn.predict(X_test)
y_pred_classes = [np.argmax(element) for element in y_pred]

print("Classification Report: \n", classification_report(y_test, y_classes))

Classification Report: 
               precision    recall  f1-score   support

           0       0.77      0.73      0.75      1000
           1       0.80      0.83      0.82      1000
           2       0.62      0.56      0.59      1000
           3       0.51      0.48      0.49      1000
           4       0.62      0.65      0.64      1000
           5       0.55      0.66      0.60      1000
           6       0.78      0.78      0.78      1000
           7       0.79      0.71      0.75      1000
           8       0.79      0.78      0.79      1000
           9       0.78      0.79      0.78      1000

    accuracy                           0.70     10000
   macro avg       0.70      0.70      0.70     10000
weighted avg       0.70      0.70      0.70     10000

